name: Deploy AWS Stack

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  aws_cdk:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install CDK Dependencies
        working-directory: ./cdk
        run: bun install

      - name: Install Lambda Dependencies
        working-directory: ./cdk/lambda
        run: bun install

      - name: Run Lambda Tests
        working-directory: ./cdk/lambda
        run: bun test

      - name: Install CLI Tool
        run: bun add -g aws-cdk

      - name: Generate JS Lambda
        working-directory: ./cdk
        run: bun build lambda/lambda_handler.ts --outfile=lambda/lambda_handler.js --target=node --format=cjs

      #   USE AS NEEDED  #
      # - name: CDK Bootstrap
      #   working-directory: ./cdk
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     AWS_REGION: us-east-1
      #   run: bunx cdk bootstrap

      - name: CDK Deploy
        working-directory: ./cdk
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
        run: bunx cdk deploy --require-approval never